# Имя рабочего процесса, которое будет отображаться на вкладке Actions репозитория.
name: golang-pipeline
# Какие события могут вызывать запуск рабочего процесса
on: push
# Группирует все задания, которые выполняются в рабочем процессе
jobs: 
  # Определяет задание test. Дочерние ключи будут определять свойства этого задания.
  test:
    # Запускает раннера в последней версии Ubuntu Linux runner
    runs-on: ubuntu-latest
    # Добавляет и запускает Docker-контейнер
    container: golang:1.25
    # Шаги задания
    steps:
        # Проверяет репозиторий, чтобы рабочий процесс мог получить к нему доступ
        - uses: actions/checkout@v4

        # Имя шага
        - name: Run Unit Tests
        # Команда для запуска. Запускает GO-тесты которые были написаны
          run: GOOS=linux GOARCH=amd64 go test

        # На этом шаге будет запускаться команда go vet, чтобы проверить код на наличие ошибок.
        - name: Vet
        # Запускает команду go vet.
          run: |
            go vet ./...