# Имя рабочего процесса, которое будет отображаться на вкладке Actions репозитория.
name: golang-pipeline
# Какие события могут вызывать запуск рабочего процесса
on: push
# Группирует все задания, которые выполняются в рабочем процессе
jobs: 
  # Определяет задание test. Дочерние ключи будут определять свойства этого задания.
  test:
    # Запускает раннера в последней версии Ubuntu Linux runner
    runs-on: ubuntu-latest
    # Добавляет и запускает Docker-контейнер
    container: golang:1.25
    # Шаги задания
    steps:
        # Проверяет репозиторий, чтобы рабочий процесс мог получить к нему доступ
        - uses: actions/checkout@v4

        # Имя шага
        - name: Run Unit Tests
        # Команда для запуска. Запускает GO-тесты которые были написаны
          run: GOOS=linux GOARCH=amd64 go test

        # На этом шаге будет запускаться команда go vet, чтобы проверить код на наличие ошибок.
        - name: Vet
        # Запускает команду go vet.
          run: |
            go vet ./...

  # название задания
  deploy:
    # Эта строка будет выводиться как заголовок задания в GitHub Actions.
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    # Задание deploy запустится только после успешного завершения задания test.
    needs: test
    # запустится только в случае указания тега для коммита, который вы пушите в GitHub.
    if: startsWith(github.ref, 'refs/tags')
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        # Это действие создаст и загрузит конструктор, который можно использовать на следующих этапах вашего рабочего процесса
        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v3

        #  Действие GitHub для входа в DockerHub.
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with: 
            # Имя пользователя DockerHub, которое вы добавляли в секреты.
            username: ${{ secrets.DOCKER_USERNAME }}
            # Токен, который вы генерировали в DockerHub, а потом сохранили в секретах репозитория.
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}


        - name: Extract metadata (tags, labels) for Docker
          id: meta
          # Это нужно для того, чтобы добавить тег к имени образа вашего приложения в DockerHub.
          uses: docker/metadata-action@v5.5.1
          with:
            # Имя вашего Docker-образа, который вы будете пушить в DockerHub.
            images: starl1ng/hello-golang

        - name: Build and push Docker Image
        # Действие GitHub для сборки Docker образа и отправки его в DockerHub.
          uses: docker/build-push-action@v5
          with:
            # Контекст для сборки образа. В данном случае текущий каталог. 
            context: .
            # при успешной сборке образа, нужно будет запушить его в DockerHub.
            push: true
            # из шага выше, которому присвоен id meta, получает тег, чтобы добавить его к имени вашего образа.
            tags: ${{ steps.meta.outputs.tags }}
            # получает метку, чтобы добавить её к вашему образу. Но у вас меток нет.
            labels: ${{ steps.meta.outputs.labels }}